// Code generated by protoc-gen-go. DO NOT EDIT.
// source: history.proto

/*
Package history is a generated protocol buffer package.

It is generated from these files:
	history.proto

It has these top-level messages:
	HistoryEntry
	HistoryLog
*/
package history

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type HistoryEntry struct {
	LineNumber string `protobuf:"bytes,2,opt,name=lineNumber" json:"lineNumber,omitempty"`
	Data       string `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
	TimeStamp  string `protobuf:"bytes,4,opt,name=timeStamp" json:"timeStamp,omitempty"`
	Context    string `protobuf:"bytes,5,opt,name=context" json:"context,omitempty"`
}

func (m *HistoryEntry) Reset()                    { *m = HistoryEntry{} }
func (m *HistoryEntry) String() string            { return proto.CompactTextString(m) }
func (*HistoryEntry) ProtoMessage()               {}
func (*HistoryEntry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *HistoryEntry) GetLineNumber() string {
	if m != nil {
		return m.LineNumber
	}
	return ""
}

func (m *HistoryEntry) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *HistoryEntry) GetTimeStamp() string {
	if m != nil {
		return m.TimeStamp
	}
	return ""
}

func (m *HistoryEntry) GetContext() string {
	if m != nil {
		return m.Context
	}
	return ""
}

type HistoryLog struct {
	History []*HistoryEntry `protobuf:"bytes,1,rep,name=history" json:"history,omitempty"`
}

func (m *HistoryLog) Reset()                    { *m = HistoryLog{} }
func (m *HistoryLog) String() string            { return proto.CompactTextString(m) }
func (*HistoryLog) ProtoMessage()               {}
func (*HistoryLog) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *HistoryLog) GetHistory() []*HistoryEntry {
	if m != nil {
		return m.History
	}
	return nil
}

func init() {
	proto.RegisterType((*HistoryEntry)(nil), "history.HistoryEntry")
	proto.RegisterType((*HistoryLog)(nil), "history.HistoryLog")
}

func init() { proto.RegisterFile("history.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 163 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0xc8, 0x2c, 0x2e,
	0xc9, 0x2f, 0xaa, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x87, 0x72, 0x95, 0xaa, 0xb8,
	0x78, 0x3c, 0x20, 0x4c, 0xd7, 0xbc, 0x92, 0xa2, 0x4a, 0x21, 0x39, 0x2e, 0xae, 0x9c, 0xcc, 0xbc,
	0x54, 0xbf, 0xd2, 0xdc, 0xa4, 0xd4, 0x22, 0x09, 0x26, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x24, 0x11,
	0x21, 0x21, 0x2e, 0x96, 0x94, 0xc4, 0x92, 0x44, 0x09, 0x66, 0xb0, 0x0c, 0x98, 0x2d, 0x24, 0xc3,
	0xc5, 0x59, 0x92, 0x99, 0x9b, 0x1a, 0x5c, 0x92, 0x98, 0x5b, 0x20, 0xc1, 0x02, 0x96, 0x40, 0x08,
	0x08, 0x49, 0x70, 0xb1, 0x27, 0xe7, 0xe7, 0x95, 0xa4, 0x56, 0x94, 0x48, 0xb0, 0x82, 0xe5, 0x60,
	0x5c, 0x25, 0x5b, 0x2e, 0x2e, 0xa8, 0xdd, 0x3e, 0xf9, 0xe9, 0x42, 0xfa, 0x5c, 0x30, 0x47, 0x49,
	0x30, 0x2a, 0x30, 0x6b, 0x70, 0x1b, 0x89, 0xea, 0xc1, 0xdc, 0x8c, 0xec, 0xc2, 0x20, 0x98, 0xaa,
	0x24, 0x36, 0xb0, 0x57, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x7c, 0xd7, 0x43, 0xaf, 0xdb,
	0x00, 0x00, 0x00,
}
